### PR TITLE
Test on CI with gyp on GCC 4.8

### PR DESCRIPTION
**Pull request by kylef**
GCC 4.8 is the oldest compiler we support with gyp (in Protagonist) and we've introduced compiler support regressions such as https://github.com/apiaryio/drafter/pull/691. This can be avoided in the future if we CI against this version.

### CODE REVIEW

**Comment by kylef** [comment]
@tjanc any ideas why this would fail on CI? Yet the same code compiles on GCC 4.8.4 elsewhere with Protagonist on Travis CI.

```
../src/refract/JsonSchema.cc:678:55: error: missing initializer for member '{anonymous}::ObjectSchema::properties' [-Werror=missing-field-initializers]
                             ObjectSchema optionSchema{};
```
