### ISSUE TITLE
C++ error: default-arguments are not allowed on this symbol

### ISSUE THREAD

**Issue by andresmoschini** [apiaryio/drafter#149]
It seems that there is an [Error C2383](https://msdn.microsoft.com/en-us/library/y81x4ttb.aspx) in [SerializeAST.cc lines 596](https://github.com/apiaryio/drafter/blob/master/src/SerializeAST.cc#L596) and [600](https://github.com/apiaryio/drafter/blob/master/src/SerializeAST.cc#L600)

Do you have a quick workaround to allow me to build it?

**Complete output:**

```
C:\Projects\drafter>vcbuild.bat
creating config.gypi
creating config.mk
creating makefiles
Warning: Missing input files:
./build\ext\snowcrash\..\..\..\ext\snowcrash\src\Version.h
All OK.
Project files generated.
Building Snow Crash...
Build started 10/16/2015 10:16:41 AM.
     1>Project "C:\Projects\drafter\build\drafter.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|Win32".
     1>Project "C:\Projects\drafter\build\drafter.sln" (1) is building "C:\Projects\drafter\build\test-libdrafter.vcxpr
       oj.metaproj" (3) on node 1 (default targets).
     3>Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (3) is building "C:\Projects\drafter\build\
       libsos.vcxproj" (4) on node 1 (default targets).
     4>InitializeBuildStatus:
         Creating "Release\obj\libsos\libsos.unsuccessfulbuild" because "AlwaysCreate" was specified.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libsos.vcxproj -> C:\Projects\drafter\build\Release\lib\libsos.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libsos\libsos.unsuccessfulbuild".
         Touching "Release\obj\libsos\libsos.lastbuildstate".
     4>Done Building Project "C:\Projects\drafter\build\libsos.vcxproj" (default targets).
     3>Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (3) is building "C:\Projects\drafter\build\
       ext\snowcrash\libsnowcrash.vcxproj" (5) on node 1 (default targets).
     5>InitializeBuildStatus:
         Creating "Release\obj\libsnowcrash\libsnowcrash.unsuccessfulbuild" because "AlwaysCreate" was specified.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libsnowcrash.vcxproj -> C:\Projects\drafter\build\Release\lib\libsnowcrash.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libsnowcrash\libsnowcrash.unsuccessfulbuild".
         Touching "Release\obj\libsnowcrash\libsnowcrash.lastbuildstate".
     5>Done Building Project "C:\Projects\drafter\build\ext\snowcrash\libsnowcrash.vcxproj" (default targets).
     3>Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (3) is building "C:\Projects\drafter\build\
       ext\snowcrash\libmarkdownparser.vcxproj" (6) on node 1 (default targets).
     6>InitializeBuildStatus:
         Creating "Release\obj\libmarkdownparser\libmarkdownparser.unsuccessfulbuild" because "AlwaysCreate" was specif
         ied.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libmarkdownparser.vcxproj -> C:\Projects\drafter\build\Release\lib\libmarkdownparser.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libmarkdownparser\libmarkdownparser.unsuccessfulbuild".
         Touching "Release\obj\libmarkdownparser\libmarkdownparser.lastbuildstate".
     6>Done Building Project "C:\Projects\drafter\build\ext\snowcrash\libmarkdownparser.vcxproj" (default targets).
     3>Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (3) is building "C:\Projects\drafter\build\
       ext\snowcrash\libsundown.vcxproj" (7) on node 1 (default targets).
     7>InitializeBuildStatus:
         Creating "Release\obj\libsundown\libsundown.unsuccessfulbuild" because "AlwaysCreate" was specified.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libsundown.vcxproj -> C:\Projects\drafter\build\Release\lib\libsundown.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libsundown\libsundown.unsuccessfulbuild".
         Touching "Release\obj\libsundown\libsundown.lastbuildstate".
     7>Done Building Project "C:\Projects\drafter\build\ext\snowcrash\libsundown.vcxproj" (default targets).
     1>Project "C:\Projects\drafter\build\drafter.sln" (1) is building "C:\Projects\drafter\build\drafter.vcxproj.metap
       roj" (2) on node 1 (default targets).
     2>Project "C:\Projects\drafter\build\drafter.vcxproj.metaproj" (2) is building "C:\Projects\drafter\build\libdraft
       er.vcxproj" (8) on node 2 (default targets).
     8>InitializeBuildStatus:
         Creating "Release\obj\libdrafter\libdrafter.unsuccessfulbuild" because "AlwaysCreate" was specified.
       ClCompile:
         C:\Program Files\Microsoft Visual Studio 11.0\VC\bin\CL.exe /c /I"..\ext\snowcrash\ext\markdown-parser\src" /I
         "..\ext\snowcrash\ext\markdown-parser\ext\sundown\src" /I..\ext\sos\src /I..\ext\snowcrash\src /Zi /nologo /W1
          /WX- /Od /Ob2 /Oi /Ot /Oy /GL /D BUILDING_SNOWCRASH=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO
         _DEPRECATE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"Release\obj\libdrafter\\" /Fd"R
         elease\obj\libdrafter\vc110.pdb" /Gd /TP /analyze- /errorReport:queue /MP ..\src\SerializeAST.cc
         SerializeAST.cc
     8>..\src\SerializeAST.cc(596): error C2383: 'Functor' : default-arguments are not allowed on this symbol [C:\Proje
       cts\drafter\build\libdrafter.vcxproj]
     8>..\src\SerializeAST.cc(600): error C2383: 'Functor' : default-arguments are not allowed on this symbol [C:\Proje
       cts\drafter\build\libdrafter.vcxproj]
     8>Done Building Project "C:\Projects\drafter\build\libdrafter.vcxproj" (default targets) -- FAILED.
     2>Done Building Project "C:\Projects\drafter\build\drafter.vcxproj.metaproj" (default targets) -- FAILED.
     3>Done Building Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (default targets) -- FAILED.
     1>Done Building Project "C:\Projects\drafter\build\drafter.sln" (default targets) -- FAILED.

Build FAILED.

Time Elapsed 00:00:03.12
```

**Comment by pksunkara** [comment]
Quick question, Which Visual studio version are you using?

**Comment by andresmoschini** [comment]
VS2015, but I have also intalled 2012.

It seems that the issue has been introduced in e28cbdd84a6746f5e88b1d429788aa9c28f4b23a, I am trying to build an older commit.

**Comment by pksunkara** [comment]
Apparently, this [function](https://github.com/apiaryio/drafter/blob/8e125a8adf7c6777bf91082796f41bc491f1c30c/src/SerializeAST.cc#L495) cannot have default arguments.

But that should have been caught by our Window CI appveyor.

**Comment by andresmoschini** [comment]
Commit 0612f337dc1ee8427fd2f297d2708e3f4bdbe1da builds successfully, so quick workaround is not need. Thanks for you quick response!

**Complete output:**

```
C:\Projects\drafter>vcbuild.bat
creating config.gypi
creating config.mk
creating makefiles
Warning: Missing input files:
./build\ext\snowcrash\..\..\..\ext\snowcrash\src\Version.h
All OK.
Project files generated.
Building Snow Crash...
Build started 10/16/2015 10:26:26 AM.
     1>Project "C:\Projects\drafter\build\drafter.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|Win32".
     1>Project "C:\Projects\drafter\build\drafter.sln" (1) is building "C:\Projects\drafter\build\test-libdrafter.vcxpr
       oj.metaproj" (3) on node 1 (default targets).
     3>Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (3) is building "C:\Projects\drafter\build\
       libsos.vcxproj" (4) on node 1 (default targets).
     4>InitializeBuildStatus:
         Creating "Release\obj\libsos\libsos.unsuccessfulbuild" because "AlwaysCreate" was specified.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libsos.vcxproj -> C:\Projects\drafter\build\Release\lib\libsos.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libsos\libsos.unsuccessfulbuild".
         Touching "Release\obj\libsos\libsos.lastbuildstate".
     4>Done Building Project "C:\Projects\drafter\build\libsos.vcxproj" (default targets).
     3>Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (3) is building "C:\Projects\drafter\build\
       ext\snowcrash\libsnowcrash.vcxproj" (6) on node 1 (default targets).
     6>InitializeBuildStatus:
         Creating "Release\obj\libsnowcrash\libsnowcrash.unsuccessfulbuild" because "AlwaysCreate" was specified.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libsnowcrash.vcxproj -> C:\Projects\drafter\build\Release\lib\libsnowcrash.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libsnowcrash\libsnowcrash.unsuccessfulbuild".
         Touching "Release\obj\libsnowcrash\libsnowcrash.lastbuildstate".
     6>Done Building Project "C:\Projects\drafter\build\ext\snowcrash\libsnowcrash.vcxproj" (default targets).
     3>Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (3) is building "C:\Projects\drafter\build\
       ext\snowcrash\libmarkdownparser.vcxproj" (7) on node 1 (default targets).
     7>InitializeBuildStatus:
         Creating "Release\obj\libmarkdownparser\libmarkdownparser.unsuccessfulbuild" because "AlwaysCreate" was specif
         ied.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libmarkdownparser.vcxproj -> C:\Projects\drafter\build\Release\lib\libmarkdownparser.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libmarkdownparser\libmarkdownparser.unsuccessfulbuild".
         Touching "Release\obj\libmarkdownparser\libmarkdownparser.lastbuildstate".
     1>Project "C:\Projects\drafter\build\drafter.sln" (1) is building "C:\Projects\drafter\build\drafter.vcxproj.metap
       roj" (2) on node 1 (default targets).
     2>Project "C:\Projects\drafter\build\drafter.vcxproj.metaproj" (2) is building "C:\Projects\drafter\build\libdraft
       er.vcxproj" (5) on node 2 (default targets).
     5>InitializeBuildStatus:
         Touching "Release\obj\libdrafter\libdrafter.unsuccessfulbuild".
     7>Done Building Project "C:\Projects\drafter\build\ext\snowcrash\libmarkdownparser.vcxproj" (default targets).
     3>Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (3) is building "C:\Projects\drafter\build\
       ext\snowcrash\libsundown.vcxproj" (8) on node 1 (default targets).
     8>InitializeBuildStatus:
         Creating "Release\obj\libsundown\libsundown.unsuccessfulbuild" because "AlwaysCreate" was specified.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libsundown.vcxproj -> C:\Projects\drafter\build\Release\lib\libsundown.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libsundown\libsundown.unsuccessfulbuild".
         Touching "Release\obj\libsundown\libsundown.lastbuildstate".
     8>Done Building Project "C:\Projects\drafter\build\ext\snowcrash\libsundown.vcxproj" (default targets).
     5>ClCompile:
         C:\Program Files\Microsoft Visual Studio 11.0\VC\bin\CL.exe /c /I"..\ext\snowcrash\ext\markdown-parser\src" /I
         "..\ext\snowcrash\ext\markdown-parser\ext\sundown\src" /I..\ext\sos\src /I..\ext\snowcrash\src /Zi /nologo /W1
          /WX- /Od /Ob2 /Oi /Ot /Oy /GL /D BUILDING_SNOWCRASH=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO
         _DEPRECATE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"Release\obj\libdrafter\\" /Fd"R
         elease\obj\libdrafter\vc110.pdb" /Gd /TP /analyze- /errorReport:queue /MP ..\src\cdrafter.cc ..\src\Serialize.
         cc ..\src\SerializeAST.cc ..\src\SerializeSourcemap.cc ..\src\SerializeResult.cc ..\src\RefractAPI.cc ..\src\R
         efractDataStructure.cc ..\src\RefractParseResult.cc ..\src\Render.cc
         cdrafter.cc
         Serialize.cc
         SerializeAST.cc
         SerializeSourcemap.cc
         SerializeResult.cc
         RefractAPI.cc
         RefractDataStructure.cc
         RefractParseResult.cc
     5>..\src\RefractDataStructure.cc(297): warning C4348: 'drafter::ExtractValueMember<T>::Store' : redefinition of de
       fault parameter : parameter 2 [C:\Projects\drafter\build\libdrafter.vcxproj]
                 with
                 [
                     T=ElementType
                 ]
                 ..\src\RefractDataStructure.cc(297) : see declaration of 'drafter::ExtractValueMember<T>::Store'
                 with
                 [
                     T=ElementType
                 ]
                 ..\src\RefractDataStructure.cc(512) : see reference to class template instantiation 'drafter::ExtractV
         alueMember<T>' being compiled
                 with
                 [
                     T=ElementType
                 ]
                 ..\src\RefractDataStructure.cc(641) : see reference to function template instantiation 'refract::IElem
         ent *drafter::RefractElementFromValue<T>(const mson::ValueMember &,const mson::BaseTypeName)' being compiled
                 with
                 [
                     T=refract::BooleanElement
                 ]
                 ..\src\RefractDataStructure.cc(650) : see reference to function template instantiation 'drafter::Value
         Trait::ElementType *drafter::ValueTrait::Invoke<refract::BooleanElement>(const drafter::ValueTrait::InputType
         &,const mson::BaseTypeName)' being compiled
                 ..\src\RefractDataStructure.cc(742) : see reference to function template instantiation 'refract::IElem
         ent *drafter::MsonMemberToRefract<drafter::ValueTrait>(const drafter::ValueTrait::InputType &,const mson::Base
         TypeName)' being compiled
                 ..\src\RefractDataStructure.cc(297) : see declaration of 'drafter::ExtractValueMember<T>::Store'
                 with
                 [
                     T=ElementType
                 ]
                 ..\src\RefractDataStructure.cc(297) : see declaration of 'drafter::ExtractValueMember<T>::Store'
                 with
                 [
                     T=ElementType
                 ]
                 ..\src\RefractDataStructure.cc(297) : see declaration of 'drafter::ExtractValueMember<T>::Store'
                 with
                 [
                     T=ElementType
                 ]
                 ..\src\RefractDataStructure.cc(297) : see declaration of 'drafter::ExtractValueMember<T>::Store'
                 with
                 [
                     T=ElementType
                 ]
         Render.cc
       Lib:
         C:\Program Files\Microsoft Visual Studio 11.0\VC\bin\Lib.exe /OUT:"C:\Projects\drafter\build\Release\lib\libdr
         after.lib" /NOLOGO /LTCG Release\obj\libdrafter\drafter.obj
         Release\obj\libdrafter\cdrafter.obj
         Release\obj\libdrafter\Serialize.obj
         Release\obj\libdrafter\SerializeAST.obj
         Release\obj\libdrafter\SerializeSourcemap.obj
         Release\obj\libdrafter\SerializeResult.obj
         Release\obj\libdrafter\RefractAPI.obj
         Release\obj\libdrafter\RefractDataStructure.obj
         Release\obj\libdrafter\RefractParseResult.obj
         Release\obj\libdrafter\Render.obj
         Release\obj\libdrafter\Element.obj
         Release\obj\libdrafter\SerializeCompactVisitor.obj
         Release\obj\libdrafter\SerializeVisitor.obj
         Release\obj\libdrafter\ComparableVisitor.obj
         Release\obj\libdrafter\TypeQueryVisitor.obj
         Release\obj\libdrafter\IsExpandableVisitor.obj
         Release\obj\libdrafter\ExpandVisitor.obj
         Release\obj\libdrafter\RenderJSONVisitor.obj
         Release\obj\libdrafter\Registry.obj
         libdrafter.vcxproj -> C:\Projects\drafter\build\Release\lib\libdrafter.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libdrafter\libdrafter.unsuccessfulbuild".
         Touching "Release\obj\libdrafter\libdrafter.lastbuildstate".
     5>Done Building Project "C:\Projects\drafter\build\libdrafter.vcxproj" (default targets).
     3>Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (3) is building "C:\Projects\drafter\build\
       test-libdrafter.vcxproj" (9) on node 1 (default targets).
     9>InitializeBuildStatus:
         Creating "Release\obj\test-libdrafter\test-libdrafter.unsuccessfulbuild" because "AlwaysCreate" was specified.
     2>Project "C:\Projects\drafter\build\drafter.vcxproj.metaproj" (2) is building "C:\Projects\drafter\build\drafter.
       vcxproj" (10) on node 2 (default targets).
    10>InitializeBuildStatus:
         Creating "Release\obj\drafter\drafter.unsuccessfulbuild" because "AlwaysCreate" was specified.
     9>ClCompile:
         C:\Program Files\Microsoft Visual Studio 11.0\VC\bin\CL.exe /c /I..\src /I..\test /I..\test\vendor\Catch\inclu
         de /I..\ext\snowcrash\src /I"..\ext\snowcrash\ext\markdown-parser\src" /I"..\ext\snowcrash\ext\markdown-parser
         \ext\sundown\src" /I..\ext\sos\src /Zi /nologo /W1 /WX- /Od /Ob2 /Oi /Ot /Oy /GL /D BUILDING_SNOWCRASH=1 /D WI
         N32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D WIN /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wch
         ar_t /Zc:forScope /GR /Fo"Release\obj\test-libdrafter\\" /Fd"Release\obj\test-libdrafter\vc110.pdb" /Gd /TP /a
         nalyze- /errorReport:queue /MP "..\test\test-RefractAPITest.cc" "..\test\test-RefractDataStructureTest.cc" "..
         \test\test-RefractParseResultTest.cc" "..\test\test-RenderTest.cc" "..\test\test-SerializeResult.cc" "..\test\
         test-cdrafter.cc" "..\test\test-drafter.cc"
    10>ClCompile:
         C:\Program Files\Microsoft Visual Studio 11.0\VC\bin\CL.exe /c /I..\ext\cmdline /I"..\ext\snowcrash\ext\markdo
         wn-parser\src" /I"..\ext\snowcrash\ext\markdown-parser\ext\sundown\src" /I..\ext\sos\src /I..\ext\snowcrash\sr
         c /Zi /nologo /W1 /WX- /Od /Ob2 /Oi /Ot /Oy /GL /D BUILDING_SNOWCRASH=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /
         D _CRT_NONSTDC_NO_DEPRECATE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"Release\obj\dr
         after\\" /Fd"Release\obj\drafter\vc110.pdb" /Gd /TP /analyze- /errorReport:queue /MP ..\src\main.cc
     9>ClCompile:
         test-RefractAPITest.cc
         test-RefractDataStructureTest.cc
    10>ClCompile:
         main.cc
     9>ClCompile:
         test-RefractParseResultTest.cc
         test-RenderTest.cc
    10>Link:
         C:\Program Files\Microsoft Visual Studio 11.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Projects\drafter\bui
         ld\Release\drafter.exe" /INCREMENTAL:NO /NOLOGO /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /m
         anifest:embed /PDB:"C:\Projects\drafter\build\Release\drafter.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG
         /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Projects\drafter\build\Release\drafter.lib" /MACHINE:X86 /SAFESEH
         Release\obj\drafter\main.obj
         Release\obj\drafter\config.obj
         Release\obj\drafter\reporting.obj
         C:\Projects\drafter\build\Release\lib\libdrafter.lib
         C:\Projects\drafter\build\Release\lib\libsos.lib
         C:\Projects\drafter\build\Release\lib\libsnowcrash.lib
         C:\Projects\drafter\build\Release\lib\libmarkdownparser.lib
         C:\Projects\drafter\build\Release\lib\libsundown.lib
         Generating code
     9>ClCompile:
         test-SerializeResult.cc
         test-cdrafter.cc
    10>Link:
         Finished generating code
         drafter.vcxproj -> C:\Projects\drafter\build\Release\\drafter.exe
       FinalizeBuildStatus:
         Deleting file "Release\obj\drafter\drafter.unsuccessfulbuild".
         Touching "Release\obj\drafter\drafter.lastbuildstate".
    10>Done Building Project "C:\Projects\drafter\build\drafter.vcxproj" (default targets).
     2>Done Building Project "C:\Projects\drafter\build\drafter.vcxproj.metaproj" (default targets).
     9>ClCompile:
         test-drafter.cc
       Link:
         C:\Program Files\Microsoft Visual Studio 11.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Projects\drafter\bui
         ld\Release\test-libdrafter.exe" /INCREMENTAL:NO /NOLOGO /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='fa
         lse'" /manifest:embed /PDB:"C:\Projects\drafter\build\Release\test-libdrafter.pdb" /SUBSYSTEM:CONSOLE /OPT:REF
          /OPT:ICF /LTCG /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Projects\drafter\build\Release\test-libdrafter.lib
         " /MACHINE:X86 /SAFESEH "Release\obj\test-libdrafter\test-drafter.obj"
         "Release\obj\test-libdrafter\test-cdrafter.obj"
         "Release\obj\test-libdrafter\test-SerializeResult.obj"
         "Release\obj\test-libdrafter\test-RefractDataStructureTest.obj"
         "Release\obj\test-libdrafter\test-RefractAPITest.obj"
         "Release\obj\test-libdrafter\test-RefractParseResultTest.obj"
         "Release\obj\test-libdrafter\test-RenderTest.obj"
         C:\Projects\drafter\build\Release\lib\libdrafter.lib
         C:\Projects\drafter\build\Release\lib\libsos.lib
         C:\Projects\drafter\build\Release\lib\libsnowcrash.lib
         C:\Projects\drafter\build\Release\lib\libmarkdownparser.lib
         C:\Projects\drafter\build\Release\lib\libsundown.lib
            Creating library C:\Projects\drafter\build\Release\test-libdrafter.lib and object C:\Projects\drafter\build
         \Release\test-libdrafter.exp
         Generating code
         Finished generating code
         test-libdrafter.vcxproj -> C:\Projects\drafter\build\Release\\test-libdrafter.exe
       FinalizeBuildStatus:
         Deleting file "Release\obj\test-libdrafter\test-libdrafter.unsuccessfulbuild".
         Touching "Release\obj\test-libdrafter\test-libdrafter.lastbuildstate".
     9>Done Building Project "C:\Projects\drafter\build\test-libdrafter.vcxproj" (default targets).
     3>Done Building Project "C:\Projects\drafter\build\test-libdrafter.vcxproj.metaproj" (default targets).
     1>Done Building Project "C:\Projects\drafter\build\drafter.sln" (default targets).

Build succeeded.

Time Elapsed 00:01:07.86
```

**Comment by pksunkara** [comment]
> Commit 0612f33 builds successfully, so quick workaround is not need

Well, the commit in which this was introduced does fix an important bug.

**Comment by andresmoschini** [comment]
Oh, and is it possible to get latest windows x86 binaries from Appveyor?

**Comment by kylef** [comment]
Appveyor is building from Visual Studio 2013 where as @andresmoschini was using Visual Studio 2012. Our documentation (incorrectly?) mentions that 2012 is supported.

It seems we have dropped support for MSVC2012 by using C++ features it doesn't have without realising. Would you be able to try building Drafter on MSVC2013 or newer?

@andresmoschini It's not currently possible to get hold of the build artifacts on Appveyor.

**Comment by pksunkara** [comment]
> It seems we have dropped support for MSVC2012 by using C++ features it doesn't have without realising

Maybe we can fix that?

**Comment by klokane** [comment]
I mean we should postpone it after decision about supported compilers and C++11 features

**Comment by pksunkara** [comment]
> supported compilers and C++11 features

Haven't we already decided that? We were meant to be on C++03 according to @zdne before.

**Comment by klokane** [comment]
Still not, we discus about drop support for older versions of compiler.

**Comment by pksunkara** [comment]
Unfortunately, building protagonist with node.js uses the older C++ compiler. Thus, we have to fix this issue to get protagonist working.
